title: Nostem Koempassu
description: Exploring personal sovereignty, consciousness, and analog living.
url: "https://github.com/nostem/nostem.github.io.git"  # Your GitHub Pages URL
baseurl: ""  # Empty for root domain

defaults:
  - scope:
      path: ""
    values:
      layout: "default"  # Apply default layout to all pages

collections:
  writings:  # For your essays, poems, random notes
    output: true
    permalink: /writing/:path/
  books:  # For book pages
    output: true
    permalink: /books/:path/

plugins:
  - jekyll-feed  # Optional: For RSS if you want
  - jekyll-sitemap  # Optional: For sitemap generation
  - jekyll-seo-tag  # Optional: For SEO optimization

# Exclude build folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
